name: "Issue Labeler"
on:
  issues:
    types: [opened, edited, assigned]

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write'

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.5 #May not be the latest version
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
